export const projects = [
    {
        name: "This current Website",
        date: "Apr 19,2025",
        link: [{name: "Github",url: "https://github.com/BentoTPG/mywebsitev2"},{name: "Website",url: "https://bentotpg.github.io/mywebsitev2/"}],
        description: "Better one with framework",
        tags: ["Next js","Typescript","Tailwind"],
        image: "./Projectpics/WebV2_Screenshot.png",
    },
    {
        name: "Old Portfolio Website",
        date: "Apr 1,2025",
        link: [{name: "Github",url: "https://github.com/BentoTPG/Website"},{name: "Website",url: "https://bentotpg.github.io/Website/"}],
        description: "Make without framework. CSS by Bootstrap. Weird looking ahhh",
        tags: ["HTML","Javascript","Bootstrap"],
        image: "./Projectpics/Web_Screenshot.jpg",
    },
    {
        name: "Disease Prediction (Cataract)",
        date: "Dec 26,2024",
        link: [{name: "Github",url: "https://github.com/BentoTPG/cataract-test"},{name: "Website",url: "https://bentotpg.github.io/cataract-test/"}],
        description: "Cataract prediction using machine learning from Teachable Machine",
        tags: ["HTML", "Javascript","Teachable Machine"],
        image: "./Projectpics/Cataract.png",
    },
    {
        name: "30/5 hell loop survival",
        date: "May 29,2024",
        link: [{name: "Scratch",url: "https://scratch.mit.edu/projects/1028884066"}],
        description: "Rogue-like survival game made using scratch.Created when block code training by SEAMOLEC",
        tags: ["Scratch"],
        image: "./Projectpics/hell_loop.png",
    },
    {
        name: "ESP8266-home-wifi-switch",
        date: "Feb 29, 2024",
        link: [{name: "Github",url: "https://github.com/BentoTPG/ESP8266-home-wifi-switch"}],
        description: "I use it every day and it still fine",
        tags: ["IOT","C++","ESP8266"],
        image: "./Projectpics/ESP8266-switch.png",
    },
];