import type { Metadata } from "next";
import {  IBM_Plex_Mono, VT323,Ubuntu } from "next/font/google";
import "./globals.css";
import Sidebar from "./Sidebar";
import Navbar from "./Navbar";
import { Toaster } from "react-hot-toast";

const ibmplexMono = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
  weight: "500"
});

const vt323 = VT323({
  variable: "--font-vt-323",
  subsets: ["latin"],
  weight: "400"
});

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets:["latin"],
  weight: "700"
});

export const metadata: Metadata = {
  title: "Bento's Profile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link 
          rel="icon" 
          href="/favicon_invert.ico" 
          media="(prefers-color-scheme: dark)"
        />
        <link 
          rel="icon" 
          href="/favicon.ico" 
          media="(prefers-color-scheme: white)"
        />
      </head>
      <body
        className={`${vt323.variable} ${ibmplexMono.variable} ${ubuntu.variable} antialiased md:mt-5 mx-auto max-w-7xl flex items-start justify-center md:justify-between`}
      >
        <Sidebar></Sidebar>
        <Navbar/>
        <main className="md:ml-67 flex-1 p-4 rounded-2xl pageandpoint">
          {children}
          <Toaster/>
        </main>
      </body>
    </html>
  );
}
